### ISSUE TITLE
Power supply PCBs

### ISSUE THREAD

**Issue by Cornelius-Sivertsen** [ClubRobotInsat/robot-2023#21]
# Design, ordering, testing (physical cards), and final assembly of main and secondary power supply cards.

# Todo:

## Design:

- [x] Design schematic, Primary power supply
- [x] Design schematic, Secondary power supply

## Ordering:

- [x] Order Primary power supply card
- [x] Order Secondary Power supply card

## Testing:

- [x] Test Primary power supply card
- [x] Test Secondary Power supply card

## Final assembly:

- [x] Complete final assembly, Primary power supply card
- [x] Complete final assembly, Secondary Power supply card

**Comment by Cornelius-Sivertsen** [comment]
Done.
